baseurl: "/PaymentFundamentals" # for GitHub Pages
url: "https://sherkzein.github.io" # for custom domain


collections:
  authors:
    output: true

destination: docs/

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"